// BEWARE, ALL NUMBERS 2 RAISED TO THE POWER OF 0 - 32, MAX 32 INDIVIDUAL AGENTS, MUST MATCH CONFIG-SIDE AGENT CONFIGURATION
enum eAgents
{
	//agent list
	CHOLERA 		= 1,
	INFLUENZA 		= 2,
	SALMONELLA		= 4,
	BRAIN 			= 8,
	FOOD_POISON		= 16,
	CHEMICAL_POISON	= 32,
	WOUND_AGENT		= 64,
	NERVE_AGENT		= 128,
	HEAVYMETAL		= 256,
}