enum EDayZProfilesOptions
{
	HUD,
	CROSSHAIR,
	QUICKBAR,
	SERVER_MESSAGES, //SYSTEM_CHAT_MSG ??
	USERS_CHAT, //DIRECT_CHAT_MSG
	RADIO_CHAT, //RADIO_CHAT_MSG	
	GAME_MESSAGES,
	ADMIN_MESSAGES,
	PLAYER_MESSAGES,
	SERVERINFO_DISPLAY,
	BLEEDINGINDICATION,
	CONNECTIVITY_INFO,
	HUD_BRIGHTNESS,
	HUD_VEHICLE,
	AMBIENT_MUSIC_MODE
	MAX
}